# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec для AppMonitor.exe — клиентское приложение."""

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[r'C:\code\AppMonitor'],
    binaries=[
        (r'C:\Program Files\Python\DLLs\pyexpat.pyd', '.'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\ft2font.cp314-win_amd64.pyd', 'matplotlib'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\_c_internal_utils.cp314-win_amd64.pyd', 'matplotlib'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\_image.cp314-win_amd64.pyd', 'matplotlib'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\_path.cp314-win_amd64.pyd', 'matplotlib'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\_qhull.cp314-win_amd64.pyd', 'matplotlib'),
        (r'C:\code\AppMonitor\.venv\Lib\site-packages\matplotlib\_tri.cp314-win_amd64.pyd', 'matplotlib'),
    ],
    datas=[
        ('api/web', 'api/web'),
        ('version.txt', '.'),
    ],
    hiddenimports=[
        'win32event',
        'win32api',
        'winerror',
        'PyQt5.sip',
        'qdarktheme',
        'core.database',
        'core.auth',
        'core.monitor',
        'core.role_manager',
        'core.limiter',
        'core.logger',
        'core.updater',
        'core.reporter',
        'core.notifier',
        'core.scheduler',
        'core.autostart',
        'core.self_protect',
        'ui.app_ui',
        'ui.base_ui',
        'ui.theme_manager',
        'ui.app_icon',
        'ui.styles',
        'ui.tray_manager',
        'ui.breadcrumbs',
        'ui.main_window',
        'ui.widgets.activity_table',
        'ui.widgets.bottom_bar',
        'ui.widgets.date_toolbar',
        'ui.widgets.tracked_table',
        'ui.dialogs.auth_dialogs',
        'ui.dialogs.limit_dialog',
        'ui.dialogs.settings_dialog',
        'ui.dialogs.stats_dialog',
        'ui.dialogs.update_dialog',
        'api.server',
        'api.schemas',
        'unicodedata',
        'pyexpat',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'cv2',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        'setuptools',
        'pip',
        'wheel',
        'pkg_resources',
        'test',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AppMonitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='data/appmonitor.ico',
)
