# -*- coding: utf-8 -*-
import os

os.chdir(os.path.join(os.path.dirname(__file__), '..', 'installer'))

lines = []
lines.append('!define PRODUCT_NAME "AppMonitor"')
lines.append('!define PRODUCT_VERSION "1.2.17"')
lines.append('!define PRODUCT_PUBLISHER "AppMonitor Team"')
lines.append('!define PRODUCT_WEB_SITE "https://appmonitor.local"')
lines.append('!define PRODUCT_DIR "$PROGRAMFILES64\\${PRODUCT_NAME}"')
lines.append('!define PRODUCT_UNINSTALL_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${PRODUCT_NAME}"')
lines.append('')
lines.append('Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"')
lines.append('OutFile "..\\dist\\AppMonitor_Setup_${PRODUCT_VERSION}.exe"')
lines.append('InstallDir "${PRODUCT_DIR}"')
lines.append('InstallDirRegKey HKLM "${PRODUCT_UNINSTALL_KEY}" "InstallDir"')
lines.append('ShowInstDetails show')
lines.append('ShowUnInstDetails show')
lines.append('')
lines.append('!include "MUI2.nsh"')
lines.append('!include "FileFunc.nsh"')
lines.append('!include "LogicLib.nsh"')
lines.append('')
lines.append('!insertmacro MUI_PAGE_WELCOME')
lines.append('!insertmacro MUI_PAGE_LICENSE "..\\installer\\LICENSE_ANSI.txt"')
lines.append('!insertmacro MUI_PAGE_DIRECTORY')
lines.append('!define MUI_PAGE_CUSTOMFUNCTION_SHOW unselectShortcuts')
lines.append('!insertmacro MUI_PAGE_COMPONENTS')
lines.append('!insertmacro MUI_PAGE_INSTFILES')
lines.append('!insertmacro MUI_PAGE_FINISH')
lines.append('')
lines.append('!insertmacro MUI_UNPAGE_CONFIRM')
lines.append('!insertmacro MUI_UNPAGE_INSTFILES')
lines.append('')
lines.append('!insertmacro MUI_LANGUAGE "Russian"')
lines.append('!insertmacro MUI_LANGUAGE "English"')
lines.append('')
lines.append('Var AUTORUN_FLAG')
lines.append('')
lines.append('Function .onInit')
lines.append('    StrCpy $AUTORUN_FLAG "0"')
lines.append('    ${GetParameters} $0')
lines.append('    ${GetOptions} $0 "/AUTORUN" $1')
lines.append('    IfErrors +2')
lines.append('        StrCpy $AUTORUN_FLAG "1"')
lines.append('FunctionEnd')
lines.append('')
lines.append('Function unselectShortcuts')
lines.append('    SectionSetFlags 1 0')
lines.append('    SectionSetFlags 2 0')
lines.append('    SectionSetFlags 3 0')
lines.append('FunctionEnd')
lines.append('')
lines.append('Section "!Основные файлы" SecCore')
lines.append('    SectionIn RO')
lines.append('    SetOutPath "$INSTDIR"')
lines.append('    File "..\\dist\\AppMonitor.exe"')
lines.append('    File /nonfatal "..\\data\\cert.pem"')
lines.append('    File /nonfatal "..\\data\\key.pem"')
lines.append('    File "..\\LICENSE.txt"')
lines.append("    ExecWait 'netsh advfirewall firewall add rule name=\"AppMonitor API\" dir=in action=allow protocol=TCP localport=8765'")
lines.append("    ExecWait 'netsh advfirewall firewall add rule name=\"AppMonitor Admin\" dir=in action=allow protocol=TCP localport=8766'")
lines.append('    WriteUninstaller "$INSTDIR\\Uninstall.exe"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "DisplayName" "${PRODUCT_NAME}"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "UninstallString" "$INSTDIR\\Uninstall.exe"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"')
lines.append('    WriteRegStr HKLM "${PRODUCT_UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\\AppMonitor.exe"')
lines.append('    WriteRegDWORD HKLM "${PRODUCT_UNINSTALL_KEY}" "NoModify" 1')
lines.append('    WriteRegDWORD HKLM "${PRODUCT_UNINSTALL_KEY}" "NoRepair" 1')
lines.append('    ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2')
lines.append('    IntFmt $0 "0x%08X" $0')
lines.append('    WriteRegDWORD HKLM "${PRODUCT_UNINSTALL_KEY}" "EstimatedSize" "$0"')
lines.append('SectionEnd')
lines.append('')
lines.append('Section "Ярлык в меню Пуск" SecStartMenu')
lines.append('    CreateDirectory "$SMPROGRAMS\\${PRODUCT_NAME}"')
lines.append('    CreateShortCut "$SMPROGRAMS\\${PRODUCT_NAME}\\AppMonitor.lnk" "$INSTDIR\\AppMonitor.exe" "" "$INSTDIR\\AppMonitor.exe" 0')
lines.append('    CreateShortCut "$SMPROGRAMS\\${PRODUCT_NAME}\\Удалить AppMonitor.lnk" "$INSTDIR\\Uninstall.exe" "" "$INSTDIR\\Uninstall.exe" 0')
lines.append('SectionEnd')
lines.append('')
lines.append('Section "Ярлык на рабочем столе" SecDesktop')
lines.append('    CreateShortCut "$DESKTOP\\AppMonitor.lnk" "$INSTDIR\\AppMonitor.exe" "" "$INSTDIR\\AppMonitor.exe" 0')
lines.append('SectionEnd')
lines.append('')
lines.append('Section "Автозапуск (рекомендуется)" SecAutostart')
lines.append('    WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "AppMonitor" "$INSTDIR\\AppMonitor.exe"')
lines.append('SectionEnd')
lines.append('')
lines.append('Section -PostInstall')
lines.append('    Sleep 1000')
lines.append('    Exec "$INSTDIR\\AppMonitor.exe"')
lines.append('SectionEnd')
lines.append('')
lines.append('LangString DESC_SecCore ${LANG_RUSSIAN} "Основные файлы приложения (обязательно)"')
lines.append('LangString DESC_SecCore ${LANG_ENGLISH} "Core program files (required)"')
lines.append('LangString DESC_SecStartMenu ${LANG_RUSSIAN} "Создать ярлык в меню Пуск"')
lines.append('LangString DESC_SecStartMenu ${LANG_ENGLISH} "Add shortcuts to Start Menu"')
lines.append('LangString DESC_SecDesktop ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"')
lines.append('LangString DESC_SecDesktop ${LANG_ENGLISH} "Add shortcut to Desktop"')
lines.append('LangString DESC_SecAutostart ${LANG_RUSSIAN} "Автоматически запускать AppMonitor при входе в Windows"')
lines.append('LangString DESC_SecAutostart ${LANG_ENGLISH} "Automatically start AppMonitor on Windows login"')
lines.append('')
lines.append('!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN')
lines.append('    !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} $(DESC_SecCore)')
lines.append('    !insertmacro MUI_DESCRIPTION_TEXT ${SecStartMenu} $(DESC_SecStartMenu)')
lines.append('    !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} $(DESC_SecDesktop)')
lines.append('    !insertmacro MUI_DESCRIPTION_TEXT ${SecAutostart} $(DESC_SecAutostart)')
lines.append('!insertmacro MUI_FUNCTION_DESCRIPTION_END')
lines.append('')
lines.append('Section "Uninstall"')
lines.append("    ExecWait 'taskkill /f /im AppMonitor.exe'")
lines.append("    ExecWait 'netsh advfirewall firewall delete rule name=\"AppMonitor API\"'")
lines.append("    ExecWait 'netsh advfirewall firewall delete rule name=\"AppMonitor Admin\"'")
lines.append('    DeleteRegValue HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "AppMonitor"')
lines.append('    RMDir /r "$SMPROGRAMS\\${PRODUCT_NAME}"')
lines.append('    Delete "$DESKTOP\\AppMonitor.lnk"')
lines.append('    RMDir /r "$INSTDIR"')
lines.append('    DeleteRegKey HKLM "${PRODUCT_UNINSTALL_KEY}"')
lines.append('    IfFileExists "$APPDATA\\AppMonitor\\*.*" 0 +3')
lines.append('        MessageBox MB_YESNO|MB_ICONQUESTION "Удалить данные в AppData ($APPDATA\\AppMonitor)?$\\n$\\nВнимание: будут удалены все логи и БД!" IDNO +2')
lines.append('        RMDir /r "$APPDATA\\AppMonitor"')
lines.append('SectionEnd')
lines.append('')

text = '\n'.join(lines)
with open('installer.nsi', 'w', encoding='cp1251') as f:
    f.write(text)
print('OK')
